name: 'ActionServerless'
description: Use GitHub Actions to serve a serverless service
inputs:
  filepath:  # id of input
    description: 'A file path where to read source code'
    required: false
runs:
  using: "composite"
  steps:
    - id: run-funcs
      run: python3 ${{ github.action_path }}/run_funcs.py ${{ inputs.filepath }}
      shell: bash
branding:
  icon: 'cloud'
  color: 'purple'
