name: Test run funcions to generate and serve

on: [push]

jobs:
  test_ruby_func:
    runs-on: ubuntu-latest
    name: A job to test run funcs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Run funcs
      uses: ./
      with:
        filepath: test/func_samples
    - name: Git commit
      run: |
        # git commit if there's any change
        if test -n "$(git status --porcelain 2>/dev/null)"; then
            git config --global user.email "idegorepl@gmail.com"
            git config --global user.name "B1nj0y"
            git add .
            git commit -m "Add changes"
            git push
        fi
